---
title: "Calendario"
---

|          Semana          | Fecha |              Preparaci贸n               |              Presentaci贸n              |              Material adicional               | Certamen | Trabajo Final |
|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|:---------:|
|  [1](/pages/week1.html)  | 19/08 | [](../pages/week1.html#preparaci贸n)  | [ワ](../pages/week1.html#presentaci贸n) | [](../pages/week1.html#material-adicional)  |          |               |
|  [2](/pages/week2.html)  | 26/08 | [](../pages/week2.html#preparaci贸n)  | [ワ](../pages/week2.html#presentaci贸n) | [](../pages/week2.html#material-adicional)  |          |               |
|  [3](/pages/week3.html)  | 02/09 | [](../pages/week3.html#preparaci贸n)  | [ワ](../pages/week3.html#presentaci贸n) | [](../pages/week3.html#material-adicional)  |          |               |
|  [4](/pages/week4.html)  | 09/09 | [](../pages/week4.html#preparaci贸n)  | [ワ](../pages/week4.html#presentaci贸n) | [](../pages/week4.html#material-adicional)  |          |               |
|  [5](/pages/week5.html)  | 16/09 | [](../pages/week5.html#preparaci贸n)  | [ワ](../pages/week5.html#presentaci贸n) | [](../pages/week5.html#material-adicional)  |          |               |
|  [6](/pages/week6.html)  | 30/09 | [](../pages/week6.html#preparaci贸n)  | [ワ](../pages/week6.html#presentaci贸n) | [](../pages/week6.html#material-adicional)  |        |               |
|  [7](/pages/week7.html)  | 07/10 | [](../pages/week7.html#preparaci贸n)  | [ワ](../pages/week7.html#presentaci贸n) | [](../pages/week7.html#material-adicional)  |          |               |
|  [8](/pages/week8.html)  | 14/10 | [](../pages/week8.html#preparaci贸n)  | [ワ](../pages/week8.html#presentaci贸n) | [](../pages/week8.html#material-adicional)  |          |               |
|  [9](/pages/week9.html)  | 21/10 | [](../pages/week9.html#preparaci贸n)  | [ワ](../pages/week9.html#presentaci贸n) | [](../pages/week9.html#material-adicional)  |          |               |
| [10](/pages/week10.html) | 28/10 | [](../pages/week10.html#preparaci贸n) | [ワ](../pages/week10.html#presentaci贸n) | [](../pages/week10.html#material-adicional) |          |               |
| [11](/pages/week11.html) | 04/11 | [](../pages/week11.html#preparaci贸n) | [ワ](../pages/week11.html#presentaci贸n) | [](../pages/week11.html#material-adicional) |        |             |
| [12](/pages/week12.html) | 11/11 | [](../pages/week12.html#preparaci贸n) | [ワ](../pages/week12.html#presentaci贸n) | [](../pages/week12.html#material-adicional) |          |               |
| [13](/pages/week13.html) | 18/11 | [](../pages/week13.html#preparaci贸n) | [ワ](../pages/week13.html#presentaci贸n) | [](../pages/week13.html#material-adicional) |          |               |
| [14](/pages/week14.html) | 25/11 | [](../pages/week14.html#preparaci贸n) | [ワ](../pages/week14.html#presentaci贸n) | [](../pages/week14.html#material-adicional) |          |             |
| [15](/pages/week15.html) | 02/12 | [](../pages/week15.html#preparaci贸n) | [ワ](../pages/week15.html#presentaci贸n) | [](../pages/week15.html#material-adicional) |          |               |
| [16](/pages/week16.html) | 09/12 | [](../pages/week16.html#preparaci贸n) | [ワ](../pages/week16.html#presentaci贸n) | [](../pages/week16.html#material-adicional) |          |               |
| [17](/pages/week17.html) | 16/12 | [](../pages/week17.html#preparaci贸n) | [ワ](../pages/week17.html#presentaci贸n) | [](../pages/week17.html#material-adicional) |          |             |
