---
title: "Programa del curso"
---

# Programa oficial

El programa oficial del curso está disponible [**acá**](/documents/IND163C_AN.pdf "Programa IND 163C")

# Introducción a Analytics

1. Del sistema de información de marketing al analitycs ¿Qué es Analytics? ¿Para qué sirve? ¿En
qué contexto es necesario?
2. Analytics en el mundo y en Chile.
3. Impacto social de Analytics en Chile y el mundo. 
4. Composición de perfiles de un área genérica de analytics en una empresa
nacional.

# Conceptos Básicos

1. Escuelas de probabilidad
2. Distribuciones probabilistas
3. Test de hipótesis e intervalos de confianza
4. Regresión lineal
5. Estimadores blandos y robustos
6. Técnicas básicas de segmentación
7. Reglas de asociación
8. Árboles de decisión
9. Deep learning, machine learning e inteligencia artificial.

# Lenguajes de programación y aplicaciones en la nube

1. Introducción a bases de datos
2. Introducción a Python y R
3. Introducción a Google Cloud y AWS.

# Planificación de proyectos de analitycs y aplicaciones de negocios

1. Aplicaciones transversales a la empresa.